controller_manager:
  ros__parameters:
    update_rate: 50

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ['left_wheel_joint']   # must match URDF joint name exactly
    right_wheel_names: ['right_wheel_joint']  # must match URDF joint name exactly
    wheel_separation:  0.68                   # 2 × 0.34 (your joint_origin_y)
    wheel_radius:      0.075
    odom_frame_id:     "odom"
    base_frame_id:     "base_footprint"
    enable_odom_tf:    true
    open_loop:         false
    publish_rate:      50.0
    cmd_vel_timeout: 0.5          # seconds before stopping if no command
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits:     true
        max_velocity:            0.5
        min_velocity:           -0.5
        has_acceleration_limits: true
        max_acceleration:        0.5
    angular:
      z:
        has_velocity_limits:     true
        max_velocity:            1.0
        min_velocity:           -1.0
        has_acceleration_limits: true
        max_acceleration:        1.0